version: '3.8'
services:
  # Database (PostgreSQL)
  postgres-db:
    image: postgres:15-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: mini_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  # Caching (Redis)
  redis-cache:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

  # Spring Boot App
  app:
    build: .
    container_name: ecommerce-api
    ports:
      - "9000:9000"
    depends_on:
      - postgres-db
      - redis-cache
    environment:
      - DB_URL=${DB_URL:jdbc:postgresql://postgres-db:5432/mini_ecommerce}
      - DB_USERNAME=${DB_USERNAME:postgres}
      - DB_PASSWORD=${DB_PASSWORD:123456}
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET=f1545ca030b7c3b0f7d7820196cb7fb14b9cb2a5ec4b911405cad2fa430966523c247a7c1c6553153f0e639873be291efb278ac8f1a5c68768d5401185f6f9e6