server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: Mini E-commerce API

  datasource:
    url: ${DB_URL:jdbc:postgres://localhost:5432/mini_ecommerce}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      #      host: ${REDIS_HOST:localhost}
      #      port: ${REDIS_PORT:6379}
      #      password: ${REDIS_PASSWORD:}
      url: ${REDIS_URL}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

app:
  refresh-token-expiration: 604800000 # 7 days
  access-token-expiration: 900000 # 15 minutes
  password-reset-token-expiration: 900000 # 15 minutes
  jwt-secret-key: ${JWT_SECRET:f1545ca030b7c3b0f7d7820196cb7fb14b9cb2a5ec4b911405cad2fa430966523c247a7c1c6553153f0e639873be291efb278ac8f1a5c68768d5401185f6f9e6}
  is-production: false
  frontend-url: http://localhost:5173

#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    enabled: true
#  show-actuator: true
