server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Mini E-commerce API
    version: 0.0.1
  
  # JSON Serializer & Deserializer
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  # For i18n.
  messages:
    use-code-as-default-message: true

  data:
    # Cache - Redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

    # Pagination
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 3600000
      idle-timeout: 7200000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  
  cache:
    type: redis

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  refresh-token-expiration: 604800000 # 7 days
  access-token-expiration: 604800000 # 15 minutes
  password-reset-token-expiration: 900000 # 15 minutes
  secret-key: ${SECRET_KEY}
  production: false
  frontend-url: http://localhost:5173

  # Order
  cancellation-deadline: 86400000 # 24 hours

  # Open Api Docs
  open-api-title: Mini E-commerce API Document
  open-api-prod-server: https://mini-ecommerce-api-zaiy.onrender.com
  open-api-version: v1.0.0

  # Cloudinary
  cloudinary-name: ${CLOUDINARY_NAME}
  cloudinary-api-key: ${CLOUDINARY_API_KEY}
  cloudinary-api-secret: ${CLOUDINARY_API_SECRET}
  cloudinary-url: ${CLOUDINARY_URL}

  email:
    from: noreply@miniecommerce.com
    reply-to: dev.doansamquoc@gmail.com

  oauth2:
    authorized-redirect-uris:
      - http://localhost:5173/oauth2/callback

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
  show-actuator: false
  show-oauth2-endpoints: true
  show-login-endpoint: true

# JTE
gg:
  jte:
    development-mode: true
    template-location: src/main/jte

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.cache: TRACE